addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"       % "0.11.0")
addSbtPlugin("com.codecommit"    % "sbt-github-actions" % "0.14.2")
addSbtPlugin("com.github.sbt"    % "sbt-ci-release"     % "1.5.12")
addSbtPlugin("de.heikoseeberger" % "sbt-header"         % "5.10.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"       % "2.5.2")
